/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author fatimatouray
 */
public class AndraMinaUppgifter extends javax.swing.JFrame {
    
    private InfDB idb;
    private String aid;

    /**
     * Creates new form AndraMinaUppgifter
     */
    public AndraMinaUppgifter(String aid, InfDB idb) {
        
        this.aid = aid;
        this.idb = idb;
        initComponents();
        
        
    }
    
    private void fyllData() {
        try {
            tfaid.setText(aid);
            tffornamn.setText(idb.fetchSingle("SELECT fornamn FROM Anstalld WHERE aid = '" + aid + "'"));
            tfefternamn.setText(idb.fetchSingle("SELECT efternamn FROM Anstalld WHERE aid = '" + aid + "'"));
            tfadress.setText(idb.fetchSingle("SELECT adress FROM Anstalld WHERE aid = '" + aid + "'"));
            tfepost.setText(idb.fetchSingle("SELECT epost FROM Anstalld WHERE aid = '" + aid + "'"));
            tftelefon.setText(idb.fetchSingle("SELECT telefon FROM Anstalld WHERE aid = '" + aid + "'"));
            tfansdat.setText(idb.fetchSingle("SELECT anstallddatum FROM Anstalld WHERE aid = '" + aid + "'"));
            tflosen.setText(idb.fetchSingle("SELECT losenord FROM Anstalld WHERE aid = '" + aid + "'"));
            tfavd.setText(idb.fetchSingle("SELECT avdelning FROM Anstalld WHERE aid = '" + aid + "'"));
        } catch (InfException ex) {
            System.out.println(ex.getMessage());
           
        }
    }
    
      private void uppdateraData() {
        try {
            idb.update("UPDATE Anstalld SET fornamn = '" + tffornamn.getText() + "', efternamn = '" + tfefternamn.getText() + "', adress = '" + tfadress.getText() + "', epost = '" + tfepost.getText() + "', telefon = '" + tftelefon.getText() + "', losenord = '" + tflosen.getText() + "', avdelning = '" + tfavd.getText() + "' WHERE aid = '" + aid + "'");
            
        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tffornamn = new javax.swing.JTextField();
        lbaid = new javax.swing.JLabel();
        lbfornamn = new javax.swing.JLabel();
        lbefternamn = new javax.swing.JLabel();
        lbadress = new javax.swing.JLabel();
        lbepost = new javax.swing.JLabel();
        lbtelefon = new javax.swing.JLabel();
        lbansdat = new javax.swing.JLabel();
        lblosen = new javax.swing.JLabel();
        lbavd = new javax.swing.JLabel();
        tfaid = new javax.swing.JTextField();
        tfefternamn = new javax.swing.JTextField();
        tfadress = new javax.swing.JTextField();
        tfepost = new javax.swing.JTextField();
        tftelefon = new javax.swing.JTextField();
        tfansdat = new javax.swing.JTextField();
        tflosen = new javax.swing.JTextField();
        tfavd = new javax.swing.JTextField();
        bnandralosen = new javax.swing.JButton();
        bnandratelfon = new javax.swing.JButton();
        bnandraepost = new javax.swing.JButton();
        bnandraadress = new javax.swing.JButton();
        bnsparaandringar = new javax.swing.JButton();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Mina uppgifter");

        tffornamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffornamnActionPerformed(evt);
            }
        });

        lbaid.setText("AID:");

        lbfornamn.setText("Förnamn:");

        lbefternamn.setText("Efternamn:");

        lbadress.setText("Adress:");

        lbepost.setText("Epost:");

        lbtelefon.setText("Telefon:");

        lbansdat.setText("Anställningsdatum:");

        lblosen.setText("Lösenord:");

        lbavd.setText("Avdelning:");

        tfefternamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfefternamnActionPerformed(evt);
            }
        });

        tfansdat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfansdatActionPerformed(evt);
            }
        });

        tfavd.setText("jTextField9");

        bnandralosen.setText("Ändra");

        bnandratelfon.setText("Ändra");

        bnandraepost.setText("Ändra");

        bnandraadress.setText("Ändra");

        bnsparaandringar.setText("Spara");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbfornamn)
                    .addComponent(lbefternamn)
                    .addComponent(lbtelefon)
                    .addComponent(lbepost)
                    .addComponent(lbansdat)
                    .addComponent(lblosen)
                    .addComponent(lbavd)
                    .addComponent(lbadress)
                    .addComponent(lbaid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tflosen)
                                .addGap(99, 99, 99)
                                .addComponent(bnandralosen))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tftelefon)
                                    .addComponent(tfepost)
                                    .addComponent(tfadress))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bnandraadress, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bnandraepost, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bnandratelfon, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(jLabel1))
                                .addComponent(tfaid)
                                .addComponent(tffornamn)
                                .addComponent(tfefternamn)
                                .addComponent(tfansdat)
                                .addComponent(tfavd))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(313, 313, 313)
                                .addComponent(bnsparaandringar)))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbaid)
                    .addComponent(tfaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbfornamn)
                    .addComponent(tffornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbefternamn)
                    .addComponent(tfefternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbadress)
                    .addComponent(tfadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnandraadress))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbepost)
                    .addComponent(tfepost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnandraepost))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtelefon)
                    .addComponent(tftelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnandratelfon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbansdat)
                    .addComponent(tfansdat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblosen)
                    .addComponent(tflosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnandralosen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbavd)
                    .addComponent(tfavd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bnsparaandringar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfansdatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfansdatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfansdatActionPerformed

    private void tffornamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffornamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffornamnActionPerformed

    private void tfefternamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfefternamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfefternamnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AndraMinaUppgifter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnandraadress;
    private javax.swing.JButton bnandraepost;
    private javax.swing.JButton bnandralosen;
    private javax.swing.JButton bnandratelfon;
    private javax.swing.JButton bnsparaandringar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel lbadress;
    private javax.swing.JLabel lbaid;
    private javax.swing.JLabel lbansdat;
    private javax.swing.JLabel lbavd;
    private javax.swing.JLabel lbefternamn;
    private javax.swing.JLabel lbepost;
    private javax.swing.JLabel lbfornamn;
    private javax.swing.JLabel lblosen;
    private javax.swing.JLabel lbtelefon;
    private javax.swing.JTextField tfadress;
    private javax.swing.JTextField tfaid;
    private javax.swing.JTextField tfansdat;
    private javax.swing.JTextField tfavd;
    private javax.swing.JTextField tfefternamn;
    private javax.swing.JTextField tfepost;
    private javax.swing.JTextField tffornamn;
    private javax.swing.JTextField tflosen;
    private javax.swing.JTextField tftelefon;
    // End of variables declaration//GEN-END:variables
}
