/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;

//Det går inte att ändra aid eller avdelning, för att man är handläggare
/**
 *
 * @author fatimatouray
 */
public class AndraMinaUppgifter extends javax.swing.JFrame {

    private InfDB idb;
    private String aid;

    /**
     * Creates new form AndraMinaUppgifter
     */
    public AndraMinaUppgifter(InfDB idb, String aid) {

        this.aid = aid;
        this.idb = idb;
        initComponents();

        bnsparaandringar.setText("Spara ändringar");
        bnsparaandringar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnsparaandringarActionPerformed(evt);
            }
        });

    }
     // Metod för de fält där man kan ändra värdet 
    public void andraUppgift() {
        try {
            tfaid.setText(aid);
            tffornamn.setText(idb.fetchSingle("SELECT fornamn FROM Anstalld WHERE aid = '" + aid + "'"));
            tfefternamn.setText(idb.fetchSingle("SELECT efternamn FROM Anstalld WHERE aid = '" + aid + "'"));
            tfadress.setText(idb.fetchSingle("SELECT adress FROM Anstalld WHERE aid = '" + aid + "'"));
            tfepost.setText(idb.fetchSingle("SELECT epost FROM Anstalld WHERE aid = '" + aid + "'"));
            tftelefon.setText(idb.fetchSingle("SELECT telefon FROM Anstalld WHERE aid = '" + aid + "'"));
            tfansdat.setText(idb.fetchSingle("SELECT anstallningsdatum FROM Anstalld WHERE aid = '" + aid + "'"));
            tflosen.setText(idb.fetchSingle("SELECT losenord FROM Anstalld WHERE aid = '" + aid + "'"));
            tfavd.setText(idb.fetchSingle("SELECT avdelning FROM Anstalld WHERE aid = '" + aid + "'"));
        } catch (InfException ex) {
            System.out.println(ex.getMessage());

        }
    }
    // //// Metod för att uppdatera handläggare och projektledares uppgifter i databasen
    private void uppdateraUppgift() {
        try {
            idb.update("UPDATE Anstalld SET fornamn = '" + tffornamn.getText() + "', efternamn = '" + tfefternamn.getText() + "', adress = '" + tfadress.getText() + "', epost = '" + tfepost.getText() + "', telefon = '" + tftelefon.getText() + "', losenord = '" + tflosen.getText() + "', avdelning = '" + tfavd.getText() + "' WHERE aid = '" + aid + "'");

        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tffornamn = new javax.swing.JTextField();
        lbaid = new javax.swing.JLabel();
        lbfornamn = new javax.swing.JLabel();
        lbefternamn = new javax.swing.JLabel();
        lbadress = new javax.swing.JLabel();
        lbepost = new javax.swing.JLabel();
        lbtelefon = new javax.swing.JLabel();
        lbansdat = new javax.swing.JLabel();
        lblosen = new javax.swing.JLabel();
        lbavd = new javax.swing.JLabel();
        tfaid = new javax.swing.JTextField();
        tfefternamn = new javax.swing.JTextField();
        tfadress = new javax.swing.JTextField();
        tfepost = new javax.swing.JTextField();
        tftelefon = new javax.swing.JTextField();
        tfansdat = new javax.swing.JTextField();
        tflosen = new javax.swing.JTextField();
        tfavd = new javax.swing.JTextField();
        bnsparaandringar = new javax.swing.JButton();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Mina uppgifter");

        lbaid.setText("AID:");

        lbfornamn.setText("Förnamn:");

        lbefternamn.setText("Efternamn:");

        lbadress.setText("Adress:");

        lbepost.setText("Epost:");

        lbtelefon.setText("Telefon:");

        lbansdat.setText("Anställningsdatum:");

        lblosen.setText("Lösenord:");

        lbavd.setText("Avdelning:");

        bnsparaandringar.setText("Spara ändringar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbfornamn)
                    .addComponent(lbefternamn)
                    .addComponent(lbtelefon)
                    .addComponent(lbepost)
                    .addComponent(lbansdat)
                    .addComponent(lblosen)
                    .addComponent(lbavd)
                    .addComponent(lbadress)
                    .addComponent(lbaid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(bnsparaandringar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfaid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                        .addComponent(tffornamn, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfefternamn, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfadress, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfepost, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tftelefon, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfansdat, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tflosen, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfavd, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbaid)
                    .addComponent(tfaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbfornamn)
                    .addComponent(tffornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbefternamn)
                    .addComponent(tfefternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbadress)
                    .addComponent(tfadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbepost)
                    .addComponent(tfepost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtelefon)
                    .addComponent(tftelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbansdat)
                    .addComponent(tfansdat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblosen)
                    .addComponent(tflosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbavd)
                    .addComponent(tfavd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(bnsparaandringar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     //metod som gör att nya ändringar sparas efter när man klickat på spara ändringar knappen
     private void bnsparaandringarActionPerformed(java.awt.event.ActionEvent evt) {
        uppdateraUppgift();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraMinaUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AndraMinaUppgifter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnsparaandringar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel lbadress;
    private javax.swing.JLabel lbaid;
    private javax.swing.JLabel lbansdat;
    private javax.swing.JLabel lbavd;
    private javax.swing.JLabel lbefternamn;
    private javax.swing.JLabel lbepost;
    private javax.swing.JLabel lbfornamn;
    private javax.swing.JLabel lblosen;
    private javax.swing.JLabel lbtelefon;
    private javax.swing.JTextField tfadress;
    private javax.swing.JTextField tfaid;
    private javax.swing.JTextField tfansdat;
    private javax.swing.JTextField tfavd;
    private javax.swing.JTextField tfefternamn;
    private javax.swing.JTextField tfepost;
    private javax.swing.JTextField tffornamn;
    private javax.swing.JTextField tflosen;
    private javax.swing.JTextField tftelefon;
    // End of variables declaration//GEN-END:variables
}
