/*
 *. Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;


public class HandläggareMeny extends javax.swing.JFrame {
    
    private InfDB idb;
    private String aid;

    /**
     * Creates new form HandläggareMeny
     */
    public HandläggareMeny(String aid, InfDB idb) {
        this.aid = aid;
        this.idb = idb;
        initComponents(); 
        
                    bnHandAvd.addActionListener(new java.awt.event.ActionListener() { // Lägg till händelselyssnare för knappen för att söka efter handläggare på avdelningen
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        bnHandAvdActionPerformed(evt);
    }
});  
    }
    
      


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        bAnsProjekt = new javax.swing.JButton();
        bAvdProj = new javax.swing.JButton();
        bAnsAvd = new javax.swing.JButton();
        bnAnsUpp = new javax.swing.JButton();
        bSeAllaProjektAvdelning = new javax.swing.JButton();
        bSokEfterProjekt = new javax.swing.JButton();
        jButton1ListaOverHalMal = new javax.swing.JButton();
        bnHandAvd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextField1.setText("Detta är handläggare menyn");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        bAnsProjekt.setText("Se mina projekt");
        bAnsProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnsProjektActionPerformed(evt);
            }
        });

        bAvdProj.setText("Se min avdelnings projekt");
        bAvdProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAvdProjActionPerformed(evt);
            }
        });

        bAnsAvd.setText("Anställda på min avdelning");
        bAnsAvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnsAvdActionPerformed(evt);
            }
        });

        bnAnsUpp.setText("Mina uppgifter");
        bnAnsUpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAnsUppActionPerformed(evt);
            }
        });

        bSeAllaProjektAvdelning.setText("Se alla projekt på min avdelning");
        bSeAllaProjektAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeAllaProjektAvdelningActionPerformed(evt);
            }
        });

        bSokEfterProjekt.setText("Sök efter projekt på datum");
        bSokEfterProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSokEfterProjektActionPerformed(evt);
            }
        });

        jButton1ListaOverHalMal.setText("Lista Över Hållbarhetsmål");
        jButton1ListaOverHalMal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ListaOverHalMalActionPerformed(evt);
            }
        });

        bnHandAvd.setText("Handläggare på min avdelning");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bnAnsUpp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAnsProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAnsAvd, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(bAvdProj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSeAllaProjektAvdelning)
                    .addComponent(bnHandAvd, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bSokEfterProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(jButton1ListaOverHalMal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAnsProjekt)
                    .addComponent(bAvdProj))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAnsAvd)
                    .addComponent(bnAnsUpp))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSeAllaProjektAvdelning)
                    .addComponent(jButton1ListaOverHalMal))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnHandAvd)
                    .addComponent(bSokEfterProjekt))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void bAnsProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnsProjektActionPerformed
        ProjektMenyAnstalld projektMeny = new ProjektMenyAnstalld(idb, aid);
        projektMeny.hamtaAllaProjekt();
        projektMeny.setVisible(true);
    }//GEN-LAST:event_bAnsProjektActionPerformed

    private void bAvdProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAvdProjActionPerformed
       Projektstatus projektstatus = new Projektstatus (idb,aid);
       projektstatus.hamtaAllaProjekt();
       projektstatus.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_bAvdProjActionPerformed


    private void personalPaAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalPaAvdelningActionPerformed
        
    }//GEN-LAST:event_personalPaAvdelningActionPerformed

    private void bAnsAvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnsAvdActionPerformed
        PersonalPa anstalld = new PersonalPa (idb, aid); 
        anstalld.setVisible (true);
    }//GEN-LAST:event_bAnsAvdActionPerformed

    private void bSeAllaProjektAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeAllaProjektAvdelningActionPerformed
        ProjektMenyAvdelning projektMenyAvdelning = new ProjektMenyAvdelning(idb, aid);
        projektMenyAvdelning.setVisible(true);
    }//GEN-LAST:event_bSeAllaProjektAvdelningActionPerformed

    private void bSokEfterProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSokEfterProjektActionPerformed
        DatumProjektSok projektDatumSok = new DatumProjektSok(idb, aid);
        projektDatumSok.setVisible(true);
    }//GEN-LAST:event_bSokEfterProjektActionPerformed

    private void jButton1ListaOverHalMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ListaOverHalMalActionPerformed
        ListaoverHallbarhetsmal listaoverHallbarhetsmal = new ListaoverHallbarhetsmal(idb);
        listaoverHallbarhetsmal.setVisible(true); 
        
   
}
     
    //Metod för att hantera händelsen när användaren klickar på knappen för att söka efter handläggare på avdelningen.
    private void bnHandAvdActionPerformed (java.awt.event.ActionEvent evt) {                                         
    HandlaggareSokning  handlaggaresokning = new HandlaggareSokning(idb, aid);
    handlaggaresokning.setVisible(true);

    
    

    }//GEN-LAST:event_jButton1ListaOverHalMalActionPerformed

    private void bnAnsUppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAnsUppActionPerformed
       AndraMinaUppgifter andraminauppgifter = new AndraMinaUppgifter(idb, aid);
       andraminauppgifter.andrauppgift();
        andraminauppgifter.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_bnAnsUppActionPerformed
// DefaultListModel<String> lista = new DefaultListModel<>();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HandläggareMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HandläggareMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HandläggareMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HandläggareMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new HandläggareMeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnsAvd;
    private javax.swing.JButton bAnsProjekt;
    private javax.swing.JButton bAvdProj;
    private javax.swing.JButton bSeAllaProjektAvdelning;
    private javax.swing.JButton bSokEfterProjekt;
    private javax.swing.JButton bnAnsUpp;
    private javax.swing.JButton bnHandAvd;
    private javax.swing.JButton jButton1ListaOverHalMal;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
