/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author mikaela nilsson
 */
public class ProjektAnsvarigMeny extends javax.swing.JFrame {

    private InfDB idb;
    private String pid;
    private String aid;

    /**
     * Creates new form ProjektAnsvarigMeny
     */
    public ProjektAnsvarigMeny(InfDB idb, String pid, String aid) {
        this.idb = idb;
        this.pid = pid;
        this.aid = aid;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        andrauppgifter = new javax.swing.JButton();
        laggtillpartner = new javax.swing.JButton();
        tabortpartner = new javax.swing.JButton();
        laggtillhandlaggare = new javax.swing.JButton();
        taborthandlaggare = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        andrauppgifter.setText("Ändra uppgifter");
        andrauppgifter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andrauppgifterActionPerformed(evt);
            }
        });

        laggtillpartner.setText("Lägg till partner");
        laggtillpartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laggtillpartnerActionPerformed(evt);
            }
        });

        tabortpartner.setText("Ta bort partner");
        tabortpartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabortpartnerActionPerformed(evt);
            }
        });

        laggtillhandlaggare.setText("Lägg till handläggare");
        laggtillhandlaggare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laggtillhandlaggareActionPerformed(evt);
            }
        });

        taborthandlaggare.setText("Ta bort handläggare");
        taborthandlaggare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taborthandlaggareActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel1.setText("Välj vad du vill göra med det valda projektet:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(andrauppgifter)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(laggtillpartner, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(tabortpartner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(laggtillhandlaggare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(taborthandlaggare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(andrauppgifter)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laggtillpartner)
                    .addComponent(laggtillhandlaggare))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tabortpartner)
                    .addComponent(taborthandlaggare))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laggtillhandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laggtillhandlaggareActionPerformed
        LaggTillHandlaggare laggTillHandlaggare = new LaggTillHandlaggare(idb, pid, aid);
        laggTillHandlaggare.setVisible(true);
    }//GEN-LAST:event_laggtillhandlaggareActionPerformed

    private void taborthandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taborthandlaggareActionPerformed
        TaBortHandlaggare taBortHandlaggare = new TaBortHandlaggare(idb, pid, aid);
        taBortHandlaggare.setVisible(true);
    }//GEN-LAST:event_taborthandlaggareActionPerformed

    private void laggtillpartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laggtillpartnerActionPerformed
        LaggTillPartnersProjektLedare laggTillPartners = new LaggTillPartnersProjektLedare(idb, pid, aid);
        laggTillPartners.setVisible(true);
    }//GEN-LAST:event_laggtillpartnerActionPerformed

    private void tabortpartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabortpartnerActionPerformed
        TaBortPartnersProjektLedare taBortpartners = new TaBortPartnersProjektLedare(idb, pid, aid);
        taBortpartners.setVisible(true);
    }//GEN-LAST:event_tabortpartnerActionPerformed

    private void andrauppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andrauppgifterActionPerformed
        AnsvarigProjektAndraUppgifter andraUppgifter = new AnsvarigProjektAndraUppgifter(idb, pid);
        andraUppgifter.setVisible(true);
    }//GEN-LAST:event_andrauppgifterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjektAnsvarigMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjektAnsvarigMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjektAnsvarigMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjektAnsvarigMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ProjektAnsvarigMeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton andrauppgifter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton laggtillhandlaggare;
    private javax.swing.JButton laggtillpartner;
    private javax.swing.JButton taborthandlaggare;
    private javax.swing.JButton tabortpartner;
    // End of variables declaration//GEN-END:variables

}
