/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author sheny
 */
public class TaBortPartnerFrame extends javax.swing.JFrame {

    private InfDB idb;
    private DefaultListModel<String> listModel;
    int pid = -1;

    public TaBortPartnerFrame(InfDB idb) {
        initComponents();
        this.idb = idb;
        try {
            String fetchUsersQuery = "SELECT * FROM ngo_2024.partner";
            ArrayList<HashMap<String, String>> resultSet = idb.fetchRows(fetchUsersQuery);

            listModel = new DefaultListModel<>();
            jList1.setModel(listModel);
            String[] keyOrder = {"pid", "namn", "kontaktperson", "kontaktepost", "telefon", "adress", "branch", "stad"};

            for (HashMap<String, String> result : resultSet) {
                // Build the list item in the specified order
                StringBuilder listItem = new StringBuilder();
                for (String key : keyOrder) {
                    String value = result.get(key);
                    if (value != null) {
                        listItem.append(key).append(": ").append(value).append(", ");
                    }
                }
                // Remove the trailing comma and space
                if (listItem.length() > 0) {
                    listItem.setLength(listItem.length() - 2);
                }
                listModel.addElement(listItem.toString());
            }
            getSelectedValueAndDelete();

        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValjPartnerSomSkaBliBorttagenText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnTaBortPartner = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValjPartnerSomSkaBliBorttagenText.setText("Välj partner som ska bli borttagen");

        jScrollPane1.setViewportView(jList1);

        btnTaBortPartner.setText("Ta bort partner");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValjPartnerSomSkaBliBorttagenText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnTaBortPartner)))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblValjPartnerSomSkaBliBorttagenText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnTaBortPartner)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void getSelectedValueAndDelete() {
        jList1.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {

                    Object selectedValue = jList1.getSelectedValue();

                    if (selectedValue != null) {
                        String[] parts = selectedValue.toString().split(", ");
                        // int aid = -1; // Initialize aid to a default value
                        for (String part : parts) {
                            String[] keyValue = part.split(": ");
                            if (keyValue[0].trim().equals("pid")) {
                                pid = Integer.parseInt(keyValue[1]);
                                break; // Exit loop once aid is found
                            }
                        }
                    }
                    String sqlFraga = "DELETE FROM NGO_2024.partner WHERE pid = '" + pid + "'";

                    btnTaBortPartner.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent e) {
                            try {
                                idb.delete(sqlFraga);
                                JOptionPane.showMessageDialog(null, "Partner har blivit borttagen!", "Information", JOptionPane.INFORMATION_MESSAGE);

                                DefaultListModel<String> model = (DefaultListModel<String>) jList1.getModel();
                                model.removeElement(selectedValue);
                                jList1.repaint();
                            } catch (InfException ex) {
                                Logger.getLogger(TaBortPartnerFrame.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    });
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaBortPartnerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortPartnerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortPartnerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortPartnerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TaBortPartnerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaBortPartner;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblValjPartnerSomSkaBliBorttagenText;
    // End of variables declaration//GEN-END:variables
}
